config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :controls, except: [:new]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
    get 'reports', to: 'reports#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  #Enums
  enum role: {:full_access => 0, :restricted_access => 1}

  # Scopes
  scope :with_full_access, -> {where(role: 0)}
  scope :with_restricted_access, -> {where(role: 1)}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def role_br
    if self.role == 'full_access'
      'Acesso Completo'
    else
      'Acesso Restrito'
    end
  end
end

app/models/control.rb
class Control < ActiveRecord::Base
  validates_presence_of :about, :mission, :vision
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #Habilita o Pundit (Autorização)
  include Pundit
  #Gerencia Erros do Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  #Layout
  layout :layout_by_resource

  private

  def user_not_authorized
    flash[:alert] = "Você não esta autorizado a executar esta ação."
    redirect_to(request.referrer || root_path)
  end

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    else
      "application"
    end
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all
    #@admins = Admin.with_restricted_access
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def edit
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador Criado Com Sucesso."
    else
      render :new
    end
  end

  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, notice: "Parâmetros Atualizado com Sucesso."
    else
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
        redirect_to backoffice_admins_path, notice: "Administrador (#{admin_email}) foi apagado com sucesso."
    else
        render :index
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/backoffice/controls_controller.rb
class Backoffice::ControlsController < BackofficeController
  before_action :set_control, only: [:edit, :update]

  def index
    @controls = Control.all
  end

  def new
    @control = Control.new
  end

  def edit
     authorize @control
  end

  def update
    if @control.update(params_control)
      redirect_to backoffice_controls_path, notice: "Parâmetros Atualizado com Sucesso."
    else
      render :edit
    end

  end

  private

  def set_control
    @control = Control.find(params[:id])
  end

  def params_control
    params.require(:control).permit(:about, :mission, :vision)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice/reports_controller.rb
class Backoffice::ReportsController < BackofficeController
  def index
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
      current_admin
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @controls = Control.all
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/controls_helper.rb
module Backoffice::ControlsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/reports_helper.rb
module Backoffice::ReportsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar Novo Usuário", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua Senha?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Alterando Campos do Administrador (#{@admin.email}) "} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administrador</h1>
<div class="panel panel-primary">
  <div class="panel-heading">
    <b>Listando os Administradores</b>

    <% if policy(@admins).new? %>
      <%= link_to new_backoffice_admin_path, class:"btn btn-success btn-circle pull-right", style:"margin-top: -5px" do %>
              <i class="fa fa-plus"></i>
      <% end %>
    <% end %>

  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
      <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>Nome</th>
                      <th>Email</th>
                      <th>Tipo de Acesso</th>
                      <th></th>
                  </tr>
              </thead>
              <tbody>
                <%  @admins.each do |admin|  %>
                  <tr>
                      <td><%=  admin.id  %></td>
                      <td><%=  admin.name  %></td>
                      <td><%=  admin.email  %></td>
                      <td><%=  admin.role_br  %></td>
                      <td><%= link_to edit_backoffice_admin_path(admin.id), class:"btn btn-success btn-circle" do %>
                        <i class="fa fa-edit"></i>
                        <% end %>
                        <% if current_admin.id != admin.id %>
                        <%= link_to backoffice_admin_path(admin.id), method: :delete , class:"btn btn-danger btn-circle", data: {confirm: "Você tem certeza que deseja excluir <b>#{admin.name}</b>?"} do %>
                          <i class="fa fa-minus"></i></td>
                        <% end %>
                        <% else %>
                            <%= link_to '#', disabled: "disabled", class:"btn btn-danger btn-circle" do %>
                            <i class="fa fa-minus"></i></td>
                        <% end %>
                      <% end %>
                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>
      <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Criando Novo Administrador"} %>

app/views/backoffice/admins/shared/_form.html.erb
          <h1 class="page-header">Administrador</h1>
            <% if @admin.errors.any? %>
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <ul>
                    <%  @admin.errors.full_messages.each do |message|  %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
              </div>
            <% end %>
              <div class="panel panel-primary">
                  <div class="panel-heading">
                     <%= action %>
                  </div>
                  <!-- /.panel-heading -->
                  <div class="panel-body">
                      <%= form_for([:backoffice, @admin]) do |f|  %>
                        <div class="form-group">
                            <label>Nome</label>
                            <%=  f.text_field :name, class:"form-control", placeholder:"Nome do Administrador" %>
                            <label>email</label>
                            <%=  f.text_field :email, class:"form-control", placeholder:"E-mail do Administrador" %>
                            <label>Senha</label>
                            <%=  f.password_field :password, class:"form-control", placeholder:"Senha" %>
                            <label>Confirmação da Senha</label>
                            <%=  f.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação da Senha" %>
                        </div>
                      <!-- /.table-responsive -->
                        <button type="submit" class="btn btn-primary">Salvar</button>
                      <% end %>
                  </div>
                  <!-- /.panel-body -->
              </div>

app/views/backoffice/controls/edit.html.erb
<%= render partial: "backoffice/controls/shared/form", locals: {action: "Alterando Textos do Site"} %>

app/views/backoffice/controls/index.html.erb
<h1 class="page-header">Configuração Site</h1>
<div class="panel panel-primary">
    <div class="panel-heading">
      <b>Textos do Site</b>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Sobre</th>
                        <th>Missão</th>
                        <th>Visão</th>
                        <th>Logo</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                  <%  @controls.each do |control|  %>
                    <tr>
                        <td><%=  control.about  %></td>
                        <td><%=  control.mission  %></td>
                        <td><%=  control.vision  %></td>
                        <td><%=  control.logo  %></td>
                        <td><%= link_to edit_backoffice_control_path(control.id), class:"btn btn-success btn-circle" do %>
                          <i class="fa fa-edit"></i></td>
                          <% end %>
                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/controls/shared/_form.html.erb
          <h1 class="page-header">Configuração Site</h1>
            <% if @control.errors.any? %>
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  <ul>
                    <%  @control.errors.full_messages.each do |message|  %>
                      <li><%=  message  %></li>
                    <% end %>
                  </ul>
              </div>
            <% end %>
              <div class="panel panel-primary">
                  <div class="panel-heading">
                     <%= action %>
                  </div>
                  <!-- /.panel-heading -->
                  <div class="panel-body">
                      <%= form_for([:backoffice, @control]) do |f|  %>
                        <div class="form-group">
                            <label>Sobre</label>
                            <%=  f.text_field :about, class:"form-control" %>
                            <label>Missão</label>
                            <%=  f.text_field :mission, class:"form-control" %>
                            <label>Visão</label>
                            <%=  f.text_field :vision, class:"form-control", :rows => 10, style: 'width:100%;' %>
                        </div>
                      <!-- /.table-responsive -->
                        <button type="submit" class="btn btn-success">Salvar</button>
                      <% end %>
                  </div>
                  <!-- /.panel-body -->
              </div>

app/views/backoffice/dashboard/index.html.erb
<h1 class="page-header">Blank</h1>

app/views/backoffice/reports/index.html.erb
<h1 class="page-header">Gerar Relatórios</h1>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Gerenciamento - IGRSS</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
    <b><%=current_admin.email%></b>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                    <li>
                    <%= link_to  destroy_admin_session_path, method: :delete do %>
                      <i class="fa fa-sign-out fa-fw"></i> Sair
                    <% end -%>
                    </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                  <%= link_to backoffice_path do %>
                      <i class="fa fa-dashboard fa-fw"></i> Dashboard
                  <% end -%>
                </li>
                <li>
                    <%= link_to backoffice_reports_path do %>
                        <i class="fa fa-list-alt fa-fw"></i> Relatórios
                    <% end %>
                </li>
                <li>
                  <%= link_to backoffice_controls_path do %>
                    <i class="fa fa-gear fa-fw"></i> Configuração Site
                  <% end %>
                </li>
                <li>
                  <%= link_to backoffice_admins_path do %>
                    <i class="fa fa-users fa-fw"></i> Administradores
                  <% end %>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/site/home/index.html.erb
<div class="jumbotron text-center">
  <h1>IGRSS</h1>
  <p>IGRSS é um sistema que calcula os indicadores de gestão dos resíduos de serviços de saúde, em atendimento à resolução RDC ANVISA nº306/04, facilitando o gerenciamento dos estabelecimentos.</p>
</div>

<!-- Container (About Section) -->
<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h2>Sobre Nossa Empresa</h2><br>
        <% @controls.each do |control| %>
          <p><%= control.about %></p>
        <% end %>
      <br><button class="btn btn-info btn-lg"><a href="#contact"><b>Entre em Contato</b></a></button>

    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div>

<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-globe logo slideanim"></span>
    </div>
    <div class="col-sm-8">
      <h2>Nossos Valores</h2><br>
      <h4><strong>Missão:</strong>
        <%  @controls.each do |control|  %>
          <%=  control.mission  %>
        </h4><br>
      <% end %>
      <h4><strong>Visão:</strong>
      <% @controls.each do |control| %>
        <%= control.vision %>
      </h4>
      <% end -%>
    </div>
  </div>
</div>

<!-- Container (Services Section) -->
<div id="services" class="container-fluid text-center">
  <h2>Serviços</h2>
  <h4>O que nós oferecemos</h4>
  <br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>POWER</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>LOVE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>JOB DONE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
  <br><br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>GREEN</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>CERTIFIED</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench logo-small"></span>
      <h4 style="color:#303030;">HARD WORK</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
</div>

<!-- Container (Portfolio Section) -->
<div id="portfolio" class="container-fluid text-center bg-grey">
  <h2>Portifólio</h2><br>
  <h4>What we have created</h4>
  <div class="row text-center slideanim">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="templates/imagens/paris.jpg" alt="Paris" width="400" height="300">
        <p><strong>Paris</strong></p>
        <p>Yes, we built Paris</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="templates/imagens/newyork.jpg" alt="New York" width="400" height="300">
        <p><strong>New York</strong></p>
        <p>We built New York</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="templates/imagens/sanfran.jpg" alt="San Francisco" width="400" height="300">
        <p><strong>San Francisco</strong></p>
        <p>Yes, San Fran is ours</p>
      </div>
    </div>
  </div><br>

<!-- Container (Pricing Section) -->
<div id="pricing" class="container-fluid">
  <div class="text-center">
    <h2>Preço</h2>
    <h4>Escolha um plano de pagamento</h4>
  </div>
  <div class="row slideanim">
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1>Básico</h1>
        </div>
        <div class="panel-body">
          <p><strong>20</strong> Lorem</p>
          <p><strong>15</strong> Ipsum</p>
          <p><strong>5</strong> Dolor</p>
          <p><strong>2</strong> Sit</p>
          <p><strong>Endless</strong> Amet</p>
        </div>
        <div class="panel-footer">
          <h3>$19</h3>
          <h4>Por Mês</h4>
          <button class="btn btn-lg">Sign Up</button>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1>Profissional</h1>
        </div>
        <div class="panel-body">
          <p><strong>50</strong> Lorem</p>
          <p><strong>25</strong> Ipsum</p>
          <p><strong>10</strong> Dolor</p>
          <p><strong>5</strong> Sit</p>
          <p><strong>Endless</strong> Amet</p>
        </div>
        <div class="panel-footer">
          <h3>$29</h3>
          <h4>Por Mês</h4>
          <button class="btn btn-lg">Sign Up</button>
        </div>
      </div>
    </div>
    <div class="col-sm-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1>Premium</h1>
        </div>
        <div class="panel-body">
          <p><strong>100</strong> Lorem</p>
          <p><strong>50</strong> Ipsum</p>
          <p><strong>25</strong> Dolor</p>
          <p><strong>10</strong> Sit</p>
          <p><strong>Endless</strong> Amet</p>
        </div>
        <div class="panel-footer">
          <h3>$49</h3>
          <h4>Por Mês</h4>
          <button class="btn btn-lg">Sign Up</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Container (Contact Section) -->
<div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">CONTATO</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Retornaremos o contato em até 24 horas.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Chicago, US</p>
      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
      <p><span class="glyphicon glyphicon-envelope"></span> myemail@something.com</p>
    </div>
    <div class="col-sm-7 slideanim">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="Nome" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="e-mail" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="Comentários" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Enviar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  jQuery.getScript('site/home');
</script>